### ISSUE TITLE
get_fill_color not responding to reactive variables with rdeck_proxy

### ISSUE THREAD

**Issue by dwachsmuth** [anthonynorth/rdeck#54]
When using rdeck_proxy to update a map in Shiny, `get_fill_color` is failing when passed a reactive input containing a column name. It gives the error message "Error in assert_rgba: get_fill_color must be a valid rgb[a] hex string". Trying to use a reactive input inside one of the scale functions also fails, with "Error in rlang::eval_tidy: object 'input' not found".

The following reprex contrasts the correct/expected behaviour when updating `pickable` with a reactive input with the incorrect/unexpected behaviour when updating `get_fill_color` with a reactive input. (The MVT tiles are publicly accessible, so you should be able to run the reprex on your end. I've also confirmed the same behaviour with a local sf file, and am happy to provide that reprex as well.)

```
# Initialize map
test_map <- 
  rdeck(initial_view_state = view_state(center =  c(-73.58, 45.53), zoom = 9)) |> 
  add_mvt_layer(id = "test",
                data = mvt_url("dwachsmuth.borough_6"),
                pickable = TRUE, 
                auto_highlight = TRUE,
                get_fill_color = canale_ind_q5_2016)

# Works
shinyApp(
  ui = fillPage(
    rdeckOutput("map", height = "100%"),
    absolutePanel(top = 10, left = 10, 
                  selectInput("pickable", label = "Pickable", 
                              choices = list("TRUE", "FALSE")
                  )
    )
  ),
  
  server = function(input, output) {
    
    output$map <- renderRdeck(test_map)
    picker <- reactive(if (input$pickable == "TRUE") TRUE else FALSE)
    
    observe({
      rdeck_proxy("map") |>
        add_mvt_layer(id = "test",
                      pickable = picker(),
                      auto_highlight = TRUE,
                      get_fill_color = canale_ind_q5_2016)
    })
  }
)

# Does not work
shinyApp(
  ui = fillPage(
    rdeckOutput("map", height = "100%"),
    absolutePanel(top = 10, left = 10, 
                  selectInput("fill", label = "Variable", choices = list(
                    canale = "canale_ind_q5_2016",
                    housing = "housing_tenant_pct_q5_2016"))
    )
  ),
  
  server = function(input, output) {
    
    output$map <- renderRdeck(test_map)
    
    observe({
      rdeck_proxy("map") |>
        add_mvt_layer(id = "test", get_fill_color = input$fill)
    })
  }
)
```

**Comment by anthonynorth** [comment]
I won't be able to run your reprex until this evening; however I think the issue is value passed isn't a name (technically, it's a call which is evaluated)

Try making a symbol out of the value (ie as.name(), or rlang::sym())

**Comment by anthonynorth** [comment]
I ran your reprex (I can't access the tiles though). The issue is `input$fill` is interpreted as a value and not a column.

The current way to deal with this is to cast as a name, then _inject_ the value with `!!` or `{{`. E.g. `get_fill_color = !!rlang::sym(input$fill)`. Once I've merged the `scales` branch, inline calls won't require the injection or curly operators.

**Comment by dwachsmuth** [comment]
This is very helpful, thanks!
