### ISSUE TITLE
Map view state

### ISSUE THREAD

**Issue by bdbmax** [anthonynorth/rdeck#57]
Hello Anthony!

Maybe you've already implemented this: is there a way to retrieve the view states from the map in R, at the moment with rdeck? States such as zoom and central point. Mapdeck does this with `input${map_id}_view_change`, I guess using `onViewStateChange` function from deck.gl. 

And thanks for your package!

**Comment by bdbmax** [comment]
My question maybe goes deeper, I'm wondering about retrieving any type of information from the deck to R, so that the zoom, bbox, a click event, etc. can be used as an input in other R calculations. There's the `pickable` argument to every layer, which I believe is used to inform a click event on an object in a pickable layer? Is this already fully implemented in rdeck, or it is only used in the hover event situation?

**Comment by anthonynorth** [comment]
Currently, `pickable` is used only for tooltips via `onHover`. I'm currently implementing feature click for shiny, it'll be ready (probably) by tomorrow.

`onViewStateChange` is trivial, that'll be ready soon also.

**Comment by bdbmax** [comment]
Great work! Thanks!

**Comment by anthonynorth** [comment]
Not finished yet. View state bounds is broken for the `viewstate` event, I'll also add util functions to retrieve these values from the input (so `input[[magic_string]]` isn't required)

**Comment by anthonynorth** [comment]
I've added [getter utilities](https://github.com/anthonynorth/rdeck/blob/04b22ff606b2d1b8658c54b6651e5f8736207508/R/shiny.R#L232-L321)  for retrieving event data from the map in shiny. 

The magic string approach will still work, but consider that to be a private api. Event names and payload structure may change in future.
