### ISSUE TITLE
Place an MVT layer under a layer present in the basemap

### ISSUE THREAD

**Issue by bdbmax** [anthonynorth/rdeck#58]
In the mapbox studio, we can slide a layer down others, makeing their labels appear on top of the MVTs. Assuming `add_mvt_layer` is translated to the `map.addLayer` function of mapbox, the latter also have the `beforeId` parameter (https://docs.mapbox.com/mapbox-gl-js/api/map/#map#addlayer), that would let us specify where the added layer appears in relation to the stack of other layers in the mapbox style.

From some documentation coming from mapbox, here is an example of how we can supply the layer under another part of the style. In this case, line geometries under the road labels:
```r
map.addLayer({
  'id': 'tiger-roads-id',
  'type': 'line',
  'source': 'tiger-roads-src',
  'source-layer': 'roads',
  'layout': {
    'line-join': 'round',
    'line-cap': 'round'
  },
  'paint': {
    'line-color': '#ff69b4',
    'line-width': 10
  }
},
'road-label');
});
```

I tried taking advantage of the `...` argument of `add_mvt_layer` and supply the `beforeId = 'road-label'`, but without success. Is this achievable in the context of rdeck?

Again, thanks for you great package!

**Comment by anthonynorth** [comment]
`rdeck` doesn't support interleaving deck.gl layers with basemap layers; all of the layers you add to an rdeck map are deck.gl layers and will be rendered on top of the basemap as an overlay. The `mvt_layer` is the deck.gl [MVTLayer](https://deck.gl/docs/api-reference/geo-layers/mvt-layer) which renders tile data as a [GeoJsonLayer](https://deck.gl/docs/api-reference/layers/geojson-layer).

You could also just use the [`layer_selector`](https://anthonynorth.github.io/rdeck/reference/rdeck.html#arguments) and toggle layers off when you need to see the basemap, unobstructed by data: `rdeck(layer_selector = TRUE)`. Assuming that your data is more important than the basemap context the majority of the time, this should work well -- my team does this.

If you need to put basemap labels on top of your data, you can achieve that by re-drawing the labels on top of other deck.gl layers with another mvt_layer (or text_layer if the data is local).

PS: I don't intend to support deck.gl and mapbox-gl interleaving via [MapboxLayer](https://deck.gl/docs/api-reference/mapbox/mapbox-layer).

**Comment by anthonynorth** [comment]
`mvt_layer` can draw text for point features via `point_type = "text"` (or "circle+text", "icon+text" etc). That tileset doesn't appear to have any point features though.

Unrelated note, changing the basemap is done via `map_style`; `theme` ("kepler" or "light") is for css -- and appears to be not validated.

```r
library(rdeck)
library(shiny)
shinyApp(
  ui = fillPage(
    rdeckOutput("map", height = "100%"),
  ),
  
  server = function(input, output) {
    
    output$map <- renderRdeck(
      rdeck(map_style = "mapbox://styles/mapbox/streets-v11",
            initial_view_state = view_state(center = c(-73.58, 45.53), 
                                            zoom = 10.1)) |> 
        add_mvt_layer(id = "test", 
                      data = mvt_url("maxbdb.borough_7"),
                      pickable = TRUE, tooltip = TRUE, 
                      get_text = rlang::sym("name"),
                      get_fill_color = "#FE7D6AFF",
                      point_type = "text")
    )
  }
)

```

**Comment by bdbmax** [comment]
That fixes the issue. Thanks a lot!
