### ISSUE TITLE
scale_custom or scale_identity for data annotation

### ISSUE THREAD

**Issue by MilesMcBain** [anthonynorth/rdeck#62]
Useful where you have a column that you know is already transformed and you want to include that in the legend generated for the scale.

```scale_identity(
  n_incidents, # already transformed
  transform_txt = "sqrt(n_incidents)"
)
```
The legend then says:

**Demand Heatmap**
colored by sqrt(incidents)

**Comment by anthonynorth** [comment]
New param for scales: `col_label`. Takes either a function with column name as input; or a string with optional "{.col}" template placeholder (which is replaced by the column name).

Examples:
```r
scale_color_power(foo_column, col_label = "sqrt({.col})")
scale_color_power(foo_column, col_label = "a new name")
scale_color_power(foo_column, col_label = snakecase::to_sentence_case)
scale_color_power(foo_column, col_label = function(col) paste0("sqrt(", col, ")"))
```
