### ISSUE TITLE
Mapbox Tokens in Shiny?

### ISSUE THREAD

**Issue by mrworthington** [anthonynorth/rdeck#63]
Hi,

I've loaded an R Deck into shinyapps.io. Everything works fine, except I can't seem to figure out a way to get my map box key to be read on shinyapps.io, so locally, you can see the mapbox tiles, but when it's hosted, the tiles are missing. Is there a way to do something akin to the following and have that token stored from the local environment onto the shiny app that gets hosted?

```r

token <- Sys.get("MAPBOX_ACCESS_TOKEN")

rdeck::mapbox_access_token(token)

```

## Local Render

<img width="1435" alt="Screen Shot 2022-04-06 at 9 24 54 PM" src="https://user-images.githubusercontent.com/8171106/162108144-35489423-92ef-4b71-a61b-b999c35728fe.png">

## Shinyapps.io

<img width="1437" alt="Screen Shot 2022-04-06 at 9 25 12 PM" src="https://user-images.githubusercontent.com/8171106/162108186-af7f2b11-ec0f-4dea-9849-76066f637cb2.png">

**Comment by anthonynorth** [comment]
Mapbox token can be set via environment variable (`MAPBOX_ACCESS_TOKEN`) or with option `rdeck.mapbox_access_token`. In shiny (own server, not shinyapps), we set the token via environment variable with `{dotenv}`.

I haven't used shinyapps, but I'm surprised it doesn't support supplying environment variables.

**Comment by mrworthington** [comment]
Got it. That's what I did. Thanks!
