### ISSUE TITLE
May I know how I can create the icon layer?

### ISSUE THREAD

**Issue by RealCoChenchao** [anthonynorth/rdeck#67]

**Comment by anthonynorth** [comment]
This layer has almost no documentation.

This layer works similarly to the text & scatter plot layers, but each feature is rendered as a raster icon. You'll need the following parameters:
- `icon_atlas`: an image sprite supplied as a url to a png (support for an in-memory image coming soon)
- `icon_mapping`: an icon index supplied as a url to a json document or a list
  See https://deck.gl/docs/api-reference/layers/icon-layer#iconmapping for schema
- `get_icon`: an [accessor](https://anthonynorth.github.io/rdeck/reference/accessor.html) to the column of `data` that contains the icon name used for each feature

An example using `spData::cycle_hire` with deck.gl example icons:

```r
library(rdeck)

icon_atlas <- "https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/icon-atlas.png"
icon_mapping <- jsonlite::fromJSON("https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/icon-atlas.json")

# ensure loaded
spData::cycle_hire

cycle_hire <- spData::cycle_hire |>
  dplyr::mutate(
    # name of icon in atlas
    icon = dplyr::if_else(
      runif(dplyr::n()) > 0.9,
      "marker-warning",
      "marker"
    )
  )

rdeck(initial_bounds = cycle_hire) |>
  add_icon_layer(
    name = "cycle hire",
    data = cycle_hire,
    get_position = sf_column(),
    size_scale = 30,
    get_color = scale_color_linear(nbikes),

    # icon params
    get_icon = icon,
    icon_atlas = icon_atlas,
    icon_mapping = icon_mapping,

    # interactivity
    pickable = TRUE,
    auto_highlight = TRUE,
    tooltip = tidyselect::everything()
  )
```

![image](https://user-images.githubusercontent.com/391385/164860968-a7ddbc54-9fc0-4aa4-91c8-61045571d918.png)
